// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://albosmefttgyvkoeuptm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYm9zbWVmdHRneXZrb2V1cHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzAwNDMsImV4cCI6MjA1OTEwNjA0M30.DjXKhBh-R8F7ChKKFhqakx3OiC3J3fhyYR6d9l6NELg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);